---
dist: trusty
language: node_js
node_js:
  - '6'
  - '8'
  - '9'

cache:
  directories:
    - node_modules

before_install:
  - touch package.json

install:
  - make install

script:
  - make lint

deploy:
  provider: npm
  email: rr.rossmann@gmail.com
  api_key:
    secure: Q7v1+sJClmjh1Xk902w5ZMOpFxwZ/7w9DKSNYkudjp6iAdcxzUqf0LkpPFnSJE+uGIE1rs3JeTdXT+3N3+ks0d4uq+vRQNdta8oRwlZ1tUOZtnAEySrBbjdVGdyIiUSRkNlnYoxlhrmh0yCaTmtt1bRZVPQtExIl00HRJ9ltcZ4gj58Y2d230e3QnUp7vW0iZew9dUzsgfh0B23vrkkm02MEjIlhhVtiWFcobh/9mruSYcSmVjg0I+HohVzuiIa0RkLfuuGL33zR8uSoR0orrWdoX3mWfQ5rpLz2WUP6hbqyQp/azkKS04Ov4iX+a16LwQM0OkNwaRRPQPAQN66LRsXA5GldlfXjMTwdFOoAc2ianb+Xp7TBVm3My2phrTYf2lVcYu92cJ4jA4j3FQOfLBelMKg5sSFNxRKds4S4kqOARH2se1TEnf7zFWQJaqM5g/tqYBXqiqbI8OsBSlmJj2m9h2g/BkY6Nzk2ekL4kgbFbAdC7w1KFvBAduSxnrGRNcIfV5Xk0ayTq3V3bLMC1dUq0e+noKjh2Uaa3E1NJUhAHbcN4UezlOo+8ggO/LRG7+B2QHamWhH4FIBPkfSiJbaZDqAvMjDbYV4jQUjad2B9Dp1AtEtNBvldWZSF8vK4xSYvpYjgrZdgnS+tdou550sSHYO8OcbmBjWFYnXTdgU=
  on:
    tags: true
    repo: Dreamscapes/eslint-import-resolver-lerna
    node_js: '8'
