---
dist: trusty
language: node_js
node_js:
  - '6'
  - '8'
  - '9'

cache:
  directories:
    - node_modules

before_install:
  - touch package.json

install:
  - make install

script:
  - make lint
